{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "180f9740-2a96-432b-9591-08394ef47477",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "import wandb\n",
    "from wandb.integration.keras import WandbMetricsLogger\n",
    "from datetime import datetime, timedelta\n",
    "from airflow import DAG\n",
    "from airflow.operators.python import PythonOperator\n",
    "import numpy as np\n",
    "import pendulum  # Airflow는 pendulum을 사용합니다\n",
    "from tensorflow.keras import layers, models\n",
    "\n",
    "# Wandb 설정\n",
    "wandb.login()\n",
    "WANDB_PROJECT = \"text\"\n",
    "WANDB_ENTITY = \"ctan0722-innodigital\"\n",
    "\n",
    "\n",
    "# 데이터 로드 및 전처리 함수\n",
    "def load_and_preprocess_data():\n",
    "    (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()\n",
    "    x_train = x_train.astype(\"float32\") / 255.0\n",
    "    x_test = x_test.astype(\"float32\") / 255.0\n",
    "    x_train = x_train[..., tf.newaxis]\n",
    "    x_test = x_test[..., tf.newaxis]\n",
    "    return (x_train, y_train), (x_test, y_test)\n",
    "\n",
    "\n",
    "# 모델 생성 함수\n",
    "def create_model(learning_rate=0.001, conv1_filters=32, conv2_filters=64):\n",
    "    model = models.Sequential([\n",
    "        layers.Conv2D(conv1_filters, (3, 3), activation='relu', input_shape=(28, 28, 1)),\n",
    "        layers.MaxPooling2D((2, 2)),\n",
    "        layers.Conv2D(conv2_filters, (3, 3), activation='relu'),\n",
    "        layers.MaxPooling2D((2, 2)),\n",
    "        layers.Flatten(),\n",
    "        layers.Dense(64, activation='relu'),\n",
    "        layers.Dense(10, activation='softmax')\n",
    "    ])\n",
    "    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),\n",
    "                  loss='sparse_categorical_crossentropy',\n",
    "                  metrics=['accuracy'])\n",
    "    return model\n",
    "\n",
    "\n",
    "# 모델 학습 함수\n",
    "def train_model(**context):\n",
    "    wandb.init(\n",
    "        project=\"mnist_classification\",\n",
    "        config={\n",
    "            \"learning_rate\": 0.001,\n",
    "            \"conv1_filters\": 32,\n",
    "            \"conv2_filters\": 64,\n",
    "            \"epochs\": 5,\n",
    "            \"batch_size\": 64\n",
    "        }\n",
    "    )\n",
    "    (x_train, y_train), (x_test, y_test) = load_and_preprocess_data()\n",
    "    config = wandb.config\n",
    "    model = create_model(\n",
    "        learning_rate=config.learning_rate,\n",
    "        conv1_filters=config.conv1_filters,\n",
    "        conv2_filters=config.conv2_filters\n",
    "    )\n",
    "    history = model.fit(\n",
    "        x_train, y_train,\n",
    "        epochs=config.epochs,\n",
    "        batch_size=config.batch_size,\n",
    "        validation_data=(x_test, y_test),\n",
    "        callbacks=[wandb.keras.WandbCallback(save_graph=False, save_model=False)]\n",
    "    )\n",
    "    test_loss, test_accuracy = model.evaluate(x_test, y_test)\n",
    "    print(f\"Test accuracy: {test_accuracy}\")\n",
    "    wandb.log({\"test_loss\": test_loss, \"test_accuracy\": test_accuracy})\n",
    "    model.save(f\"mnist_model_{datetime.now().strftime('%Y%m%d_%H%M%S')}.keras\")\n",
    "    wandb.finish()\n",
    "\n",
    "\n",
    "# 하이퍼파라미터 튜닝 함수\n",
    "def hyperparameter_sweep():\n",
    "    sweep_config = {\n",
    "        'method': 'random',\n",
    "        'metric': {'name': 'val_accuracy', 'goal': 'maximize'},\n",
    "        'parameters': {\n",
    "            'learning_rate': {'values': [0.001, 0.01, 0.0001]},\n",
    "            'conv1_filters': {'values': [16, 32, 64]},\n",
    "            'conv2_filters': {'values': [32, 64, 128]},\n",
    "            'batch_size': {'values': [64, 128, 256]}\n",
    "        }\n",
    "    }\n",
    "    sweep_id = wandb.sweep(sweep_config, project=\"text\")\n",
    "    wandb.agent(sweep_id, train_model, count=5)\n",
    "\n",
    "\n",
    "# Airflow DAG 정의\n",
    "local_tz = pendulum.timezone(\"Asia/Seoul\")\n",
    "\n",
    "default_args = {\n",
    "    'owner': 'airflow',\n",
    "    'start_date': datetime(2024, 1, 1, tzinfo=local_tz),\n",
    "    'retries': 1,\n",
    "    'retry_delay': timedelta(minutes=5),\n",
    "}\n",
    "\n",
    "dag = DAG(\n",
    "    'mnist_training_pipeline',\n",
    "    default_args=default_args,\n",
    "    description='MNIST 학습 파이프라인',\n",
    "    schedule='@daily',\n",
    "    catchup=False\n",
    ")\n",
    "\n",
    "# DAG 태스크 정의\n",
    "preprocessing_task = PythonOperator(\n",
    "    task_id='load_and_preprocess_data',\n",
    "    python_callable=load_and_preprocess_data,\n",
    "    dag=dag\n",
    ")\n",
    "\n",
    "training_task = PythonOperator(\n",
    "    task_id='train_model',\n",
    "    python_callable=train_model,\n",
    "    dag=dag\n",
    ")\n",
    "\n",
    "hyperparameter_tuning_task = PythonOperator(\n",
    "    task_id='hyperparameter_tuning',\n",
    "    python_callable=hyperparameter_sweep,\n",
    "    dag=dag\n",
    ")\n",
    "\n",
    "# 태스크 의존성 설정\n",
    "preprocessing_task >> training_task >> hyperparameter_tuning_task\n",
    "\n",
    "# Jupyter Notebook에서 직접 실행하기 위한 코드\n",
    "if __name__ == \"__main__\":\n",
    "    train_model()\n",
    "    hyperparameter_sweep()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
